### ISSUE TITLE
docker.errors.APIError

### ISSUE THREAD

**Issue by bhoslepu** [ajinkyamhatre/Docker-Dashboard#1]
Getting this error after making changes in user.py for IP to navigate from remote system:

APIError: 400 Client Error: Bad Request ("client is newer than server (client API version: 1.21, server API version: 1.19)")

Docker version:
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d/1.7.1
OS/Arch (server): linux/amd64

OS: CentOS 6.7

![docker-dashboard_error](https://cloud.githubusercontent.com/assets/3243098/14311873/43bb3e32-fc07-11e5-9cbe-e10f89b584fb.png)

**Comment by khandu443** [comment]
I am also facing the same issue on centos 6.7 64 bit

**Comment by ashwini-mhatre** [comment]
Hi all,
could you please try this app on ubuntu 14.04.

Thank you.
Regards,
Ashwini

**Comment by FranBarrera** [comment]
The same issue on debian 8.3 without any changes in user.py

**Comment by ajinkyamhatre** [comment]
this application is developed for ubuntu 14.04 
                                         thank you :)
